# -*- coding: utf-8 -*-
"""1-estatidistica-python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GP7HeE4AKPHuEQk1tG5H_ytD460QVpqS
"""

!python3 --version

!pip freeze

import numpy as np

datos = np.array([2,2,5,5,5,5,5,6,6,6,6,6,6,7,7,7,7,7,7,7])

"""# MEDIA"""

media = np.mean(datos)
print(f'La media es : {media}')

"""# MEDIANA"""

#mediana
mediana = np.median(datos)
print(f'Mediana : {mediana}')

"""# MODA"""

#moda
valores,conteos = np.unique(datos,return_counts=True)
moda = valores[np.argmax(conteos)]
print(f'Moda : {moda}')